project:
  type: website
  output-dir: docs

website:
  title: "Dades Massives"
  navbar:
    left:
      - href: index.qmd
        text: Inici
      - href: tema_01.qmd
        text: Tema 1
      - href: tema_02.qmd
        text: Tema 2

lang: ca

format:
  html:
    theme: cosmo
    toc: true