project:
  type: website
  output-dir: docs

website:
  title: "Dades Massives"
  navbar:
    left:
      - href: index.qmd
        text: Inici
      - href: tema01.qmd
        text: Tema 1
      # Cada semana añadirás una línea aquí

format:
  html:
    theme: cosmo
    toc: true