<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="ca" xml:lang="ca"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="">
<meta name="dcterms.date" content="2026-07-07">

<title>Regressió – Dades massives</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-a0f9fd0d421825b736dc1bbcbcba2219.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Cap resultat",
    "search-matching-documents-text": "documents que coincideixen",
    "search-copy-link-title": "Copia l'enllaç a la cerca",
    "search-hide-matches-text": "Amaga les coincidències addicionals",
    "search-more-match-text": "altra coincidència en aquest document",
    "search-more-matches-text": "altres coincidències en aquest document",
    "search-clear-button-title": "Neteja",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel·la",
    "search-submit-button-title": "Envia",
    "search-label": "Cerca"
  }
}</script>
<link href="site_libs/pagedtable-1.1/css/pagedtable.css" rel="stylesheet">

<script src="site_libs/pagedtable-1.1/js/pagedtable.js"></script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Dades massives</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Cerca"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Commuta la navegació" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Inici</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./tema_01.html"> 
<span class="menu-text">Tema 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./tema_02.html"> 
<span class="menu-text">Tema 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./tema_03.html"> 
<span class="menu-text">Tema 3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./tema_04.html"> 
<span class="menu-text">Tema 4</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./tema_05.html" aria-current="page"> 
<span class="menu-text">Tema 5</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./tema_06.html"> 
<span class="menu-text">Tema 6</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./tema_07.html"> 
<span class="menu-text">Tema 7</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./tema_08.html"> 
<span class="menu-text">Tema 8</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./tema_09.html"> 
<span class="menu-text">Tema 9</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./tema_10.html"> 
<span class="menu-text">Tema 10</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./tema_11.html"> 
<span class="menu-text">Tema 11</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">En aquesta pàgina</h2>
   
  <ul class="collapse">
  <li><a href="#introducció-a-laprenentatge-automàtic" id="toc-introducció-a-laprenentatge-automàtic" class="nav-link active" data-scroll-target="#introducció-a-laprenentatge-automàtic"><span class="header-section-number">1</span> Introducció a l’aprenentatge automàtic</a>
  <ul class="collapse">
  <li><a href="#regressió-i-classificació" id="toc-regressió-i-classificació" class="nav-link" data-scroll-target="#regressió-i-classificació"><span class="header-section-number">1.1</span> Regressió i classificació</a></li>
  <li><a href="#conjunt-dentrenament-i-conjunt-de-test" id="toc-conjunt-dentrenament-i-conjunt-de-test" class="nav-link" data-scroll-target="#conjunt-dentrenament-i-conjunt-de-test"><span class="header-section-number">1.2</span> Conjunt d’entrenament i conjunt de test</a></li>
  <li><a href="#sobreajust-overfitting" id="toc-sobreajust-overfitting" class="nav-link" data-scroll-target="#sobreajust-overfitting"><span class="header-section-number">1.3</span> Sobreajust (<em>overfitting</em>)</a></li>
  </ul></li>
  <li><a href="#regressió" id="toc-regressió" class="nav-link" data-scroll-target="#regressió"><span class="header-section-number">2</span> Regressió</a></li>
  <li><a href="#regressió-lineal-simple" id="toc-regressió-lineal-simple" class="nav-link" data-scroll-target="#regressió-lineal-simple"><span class="header-section-number">3</span> Regressió lineal simple</a>
  <ul class="collapse">
  <li><a href="#supòsits-de-la-regressió-lineal" id="toc-supòsits-de-la-regressió-lineal" class="nav-link" data-scroll-target="#supòsits-de-la-regressió-lineal"><span class="header-section-number">3.1</span> Supòsits de la regressió lineal</a></li>
  </ul></li>
  <li><a href="#regressió-lineal-múltiple" id="toc-regressió-lineal-múltiple" class="nav-link" data-scroll-target="#regressió-lineal-múltiple"><span class="header-section-number">4</span> Regressió lineal múltiple</a></li>
  <li><a href="#exercici" id="toc-exercici" class="nav-link" data-scroll-target="#exercici"><span class="header-section-number">5</span> Exercici</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Regressió</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Publicat</div>
    <div class="quarto-title-meta-contents">
      <p class="date">07/07/2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introducció-a-laprenentatge-automàtic" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introducció a l’aprenentatge automàtic</h1>
<p>Fins ara ens hem centrat a explorar i visualitzar dades: entendre com es distribueixen les variables, detectar relacions i representar-les gràficament. A partir d’ara, farem un pas més enllà i entrarem en el camp de l’aprenentatge automàtic (<em>machine learning</em>), que té com a objectiu construir models capaços de predir o classificar automàticament a partir de dades.</p>
<p>Dins de l’aprenentatge automàtic, es distingeix habitualment entre dos grans enfocaments:</p>
<ul>
<li>aprenentatge no supervisat: les dades no inclouen una variable «resposta» coneguda; l’objectiu és descobrir patrons o estructures ocultes en les dades (per exemple, agrupar clients amb comportaments similars sense saber prèviament a quin grup pertanyen).</li>
</ul>
<p>-aprenentatge supervisat: disposem d’una variable «resposta» coneguda per a cada observació, i l’objectiu és construir un model que aprengui la relació entre les variables predictores i aquesta resposta, de manera que puguem predir-la per a noves observacions on encara no la coneixem. És en aquest segon enfocament en el que centrarem els propers temes.</p>
<section id="regressió-i-classificació" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="regressió-i-classificació"><span class="header-section-number">1.1</span> Regressió i classificació</h2>
<p>Dins de l’aprenentatge supervisat, la naturalesa de la variable resposta determina el tipus de problema al qual ens enfrontem:</p>
<p>-quan la variable resposta és quantitativa (per exemple, un preu, una temperatura o un nivell d’assistència), parlem d’un problema de regressió. L’objectiu és predir un valor numèric el més aproximat possible al valor real.</p>
<p>-quan la variable resposta és categòrica (per exemple, si un client serà morós o no, si un correu és spam o no, o si un bolet és comestible o verinós), parlem d’un problema de classificació. L’objectiu és predir a quina categoria pertany cada observació.</p>
<p>Cal fer, però, una petita matisació: existeix un mètode anomenat regressió logística que, malgrat el seu nom, s’utilitza per resoldre problemes de classificació (habitualment amb dues categories, com «sí/no» o «morós/no morós»). S’anomena «regressió» perquè, internament, el model estima una equació de tipus lineal per calcular la probabilitat que una observació pertanyi a una categoria determinada. Aquesta probabilitat es converteix després en una predicció categòrica. És, per tant, un pont natural entre els dos mons: tècnicament és una regressió, però la seva finalitat pràctica és la classificació.</p>
<p>Als propers temes veurem exemples de tots dos tipus de problemes: la regressió lineal (simple i múltiple) ens permetrà predir variables quantitatives, mentre que els arbres de decisió i els classificadors bayesians s’utilitzen habitualment per a problemes de classificació.</p>
</section>
<section id="conjunt-dentrenament-i-conjunt-de-test" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="conjunt-dentrenament-i-conjunt-de-test"><span class="header-section-number">1.2</span> Conjunt d’entrenament i conjunt de test</h2>
<p>Un dels principis fonamentals de l’aprenentatge automàtic és que un model no s’ha d’avaluar amb les mateixes dades amb les que s’ha construït. Si ho féssim així, el model podria semblar molt precís simplement perquè ha «memoritzat» les particularitats d’aquelles dades concretes, sense que això garanteixi que funcionarà bé amb dades noves.</p>
<p>Per evitar-ho, és habitual dividir el conjunt de dades disponible en dues parts:</p>
<p>-conjunt d’entrenament (<em>training set</em>): la part de les dades que s’utilitza per construir o «entrenar» el model (normalment, entre un 70% i un 80% de les dades disponibles).</p>
<p>-conjunt de test (<em>test set</em>): la part restant de les dades, que no s’utilitza durant la construcció del model, sinó únicament per avaluar-ne el rendiment amb observacions que el model no ha «vist» prèviament.</p>
<p>Aquesta divisió ens permet obtenir una estimació més realista de com es comportarà el model quan s’apliqui a dades noves, que és, al cap i a la fi, el seu objectiu últim.</p>
</section>
<section id="sobreajust-overfitting" class="level2" data-number="1.3">
<h2 data-number="1.3" class="anchored" data-anchor-id="sobreajust-overfitting"><span class="header-section-number">1.3</span> Sobreajust (<em>overfitting</em>)</h2>
<p>Un dels riscos més habituals a l’hora de construir un model és el que es coneix com a «sobreajust» (<em>overfitting</em>). Es produeix quan un model s’ajusta tan estretament a les particularitats del conjunt d’entrenament que perd capacitat de generalitzar a dades noves. Un model amb sobreajust sol mostrar un rendiment excel·lent sobre el conjunt d’entrenament, però un rendiment molt pitjor sobre el conjunt de test.</p>
<p>El cas contrari és el de l’«infraajust» (<em>underfitting</em>), en el qual el model és massa simple per captar els patrons rellevants de les dades, i per tant obté un rendiment mediocre tant en el conjunt d’entrenament com en el de test.</p>
</section>
</section>
<section id="regressió" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Regressió</h1>
<p>La regressió és un conjunt de tècniques estadístiques que permeten modelitzar la relació entre una o més variables independents (o explicatives) i una variable dependent (o resposta).</p>
<p>En funció de quantes variables explicatives tenim i quin tipus de variable volem predir, podem distingir tres grans tipus de regressió:</p>
<ul>
<li><p>regressió lineal simple: s’utilitza quan volem explicar o predir una variable quantitativa a partir d’una única variable predictora, també quantitativa, assumint que la relació entre elles és aproximadament lineal (una recta).</p></li>
<li><p>regressió lineal múltiple: és una extensió de la regressió lineal simple en què la variable dependent quantitativa s’explica a partir de dues o més variables predictives, també quantitatives.</p></li>
<li><p>regressió logística: s’utilitza quan la variable dependent no és quantitativa sinó categòrica.</p></li>
</ul>
<p>En els següents apartats desenvoluparem les dues primeres categories (regressió lineal simple i múltiple).</p>
</section>
<section id="regressió-lineal-simple" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Regressió lineal simple</h1>
<p>Suposem que volem analitzar si la disponibilitat d’equipaments culturals (biblioteques, centres cívics, teatres, museus, etc.) en un municipi està relacionada amb l’assistència a activitats culturals.</p>
<ul>
<li><p>Variable independent (X): Equipaments culturals per 10.000 habitants</p></li>
<li><p>Variable dependent (Y): Assistència anual a activitats culturals per 1.000 habitants</p></li>
</ul>
<p>Intuitivament, podem pensar que, a més equipaments per habitant, més oportunitats i, per tant, més assistència a activitats culturals (tot i que també hi poden influir altres factors com renda, edat, turisme, programació, transport, etc.).</p>
<p>La taula mostra les dades de les dues variables per a una mostra de 10 municipis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>cultura <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">municipi =</span> <span class="fu">paste0</span>(<span class="st">"Municipi_"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>),</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>                      <span class="at">equipaments_per_10k =</span> <span class="fu">c</span>(<span class="fl">1.2</span>, <span class="fl">0.8</span>, <span class="fl">2.0</span>, <span class="fl">1.5</span>, <span class="fl">2.3</span>, <span class="fl">0.6</span>, <span class="fl">1.8</span>, <span class="fl">2.6</span>, <span class="fl">1.0</span>, <span class="fl">2.1</span>),</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>                      <span class="at">assistencia_per_1000 =</span> <span class="fu">c</span>(<span class="dv">45</span>, <span class="dv">30</span>, <span class="dv">70</span>, <span class="dv">55</span>, <span class="dv">80</span>, <span class="dv">25</span>, <span class="dv">65</span>, <span class="dv">90</span>, <span class="dv">35</span>, <span class="dv">75</span>))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>cultura</span></code></pre></div><button title="Copia al porta-retalls" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["municipi"],"name":[1],"type":["chr"],"align":["left"]},{"label":["equipaments_per_10k"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["assistencia_per_1000"],"name":[3],"type":["dbl"],"align":["right"]}],"data":[{"1":"Municipi_1","2":"1.2","3":"45"},{"1":"Municipi_2","2":"0.8","3":"30"},{"1":"Municipi_3","2":"2.0","3":"70"},{"1":"Municipi_4","2":"1.5","3":"55"},{"1":"Municipi_5","2":"2.3","3":"80"},{"1":"Municipi_6","2":"0.6","3":"25"},{"1":"Municipi_7","2":"1.8","3":"65"},{"1":"Municipi_8","2":"2.6","3":"90"},{"1":"Municipi_9","2":"1.0","3":"35"},{"1":"Municipi_10","2":"2.1","3":"75"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>La regressió lineal simple modelitza aquesta relació amb una equació del tipus:</p>
<p><span class="math display">\[
Y = a + \beta_1 X
\]</span></p>
<p>On:</p>
<ul>
<li><span class="math inline">\(a\)</span> és la intersecció (<em>intercept</em>, valor esperat de Y quan X = 0)</li>
<li><span class="math inline">\(\beta_1\)</span> és el pendent (canvi mitjà en Y per cada unitat addicional de X)</li>
</ul>
<p>Per visualitzar la possible relació, una bona idea és representar les dades en un diagrama de dispersió.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cultura<span class="sc">$</span>equipaments_per_10k, cultura<span class="sc">$</span>assistencia_per_1000,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Equipaments culturals"</span>,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Assistència a activitats culturals"</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Relació entre equipaments i assistència"</span>)</span></code></pre></div><button title="Copia al porta-retalls" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tema_05_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>El model que volem ajustar és el següent:</p>
<p><span class="math display">\[
Assistència = a + \beta_1 \cdot Equipaments
\]</span></p>
<p>Calculem el model amb R fent servir la funció <code>lm</code>. Aquesta és una funció disponible en R base, no cal instal·lar cap paquet addicional:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>model_cultura <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> assistencia_per_1000 <span class="sc">~</span> equipaments_per_10k,</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                    <span class="at">data =</span> cultura)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_cultura)</span></code></pre></div><button title="Copia al porta-retalls" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = assistencia_per_1000 ~ equipaments_per_10k, data = cultura)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.3716 -0.6352  0.1673  0.9893  1.0331 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)           4.1032     1.0446   3.928  0.00437 ** 
equipaments_per_10k  33.2684     0.6093  54.598  1.4e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.235 on 8 degrees of freedom
Multiple R-squared:  0.9973,    Adjusted R-squared:  0.997 
F-statistic:  2981 on 1 and 8 DF,  p-value: 1.405e-11</code></pre>
</div>
</div>
<p>Com hem d’interpretar les dades anteriors? El coeficient associat a la variable <em>equipaments_per_10k</em> és positiu i estadísticament significatiu (β = 33.27; p &lt; 0.001). Això indica que, de mitjana, un increment d’un equipament cultural per cada 10.000 habitants s’associa amb un augment aproximat de 33 persones per 1.000 habitants en l’assistència anual a activitats culturals. L’error estàndard del coeficient és reduït (0.61), la qual cosa indica una estimació molt precisa.</p>
<p>L’intercept del model (a = 4.10; p = 0.004) representa el nivell estimat d’assistència quan el nombre d’equipaments és zero. Tot i ser estadísticament significatiu, la seva interpretació substantiva és limitada, ja que aquest valor queda fora del rang habitual observat en les dades.</p>
<p><span class="math display">\[
Assistència = 4.1032 + 33.2684 \cdot Equipaments
\]</span></p>
<p>Pel que fa a la qualitat de l’ajust, el model presenta un coeficient de determinació molt elevat (R² = 0.997), fet que indica que el 99,7% de la variabilitat observada en l’assistència és explicada pel nombre d’equipaments culturals.</p>
<p>En conjunt, els resultats mostren una associació lineal positiva molt forta entre la disponibilitat d’equipaments culturals i la participació cultural. No obstant això, cal interpretar aquests resultats amb prudència. En primer lloc, la mostra és reduïda (n = 10). En segon lloc, el model és bivariant i no controla altres factors potencialment rellevants, com ara el nivell de renda, la composició demogràfica o el capital cultural del municipi. Per tant, els resultats descriuen una relació estadística d’associació, però no permeten establir una relació causal.</p>
<p>Per visualitzar el model, tornem a representar les dades en un diagrama de dispersió afegint-hi la línia de tendència.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(cultura<span class="sc">$</span>equipaments_per_10k, cultura<span class="sc">$</span>assistencia_per_1000,</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Equipaments culturals"</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Assistència a activitats culturals"</span>,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Relació entre equipaments i assistència"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(model_cultura, <span class="at">lwd =</span> <span class="dv">2</span>, <span class="at">col =</span> <span class="st">"blue"</span>)</span></code></pre></div><button title="Copia al porta-retalls" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tema_05_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A partir del model, podem predir l’assistència a activitats culturals per 1000 habitants d’un nou municipi amb 1.7 equipaments per 10.000 habitants de la manera següent:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>nou_municipi <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">equipaments_per_10k =</span> <span class="fl">1.7</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model_cultura, <span class="at">newdata =</span> nou_municipi)</span></code></pre></div><button title="Copia al porta-retalls" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
60.65953 </code></pre>
</div>
</div>
<p>Mitjançant la funció <code>predict()</code>, el model estima un nivell d’assistència aproximat de 60,66 persones per cada 1.000 habitants.</p>
<p>Aquesta predicció és una estimació puntual: un únic valor que representa la millor predicció del model per a aquell municipi concret. No obstant, com qualsevol estimació basada en una mostra, aquesta predicció està subjecta a incertesa i és recomanable acompanyar-la d’un interval que en reflecteixi el marge d’error, en lloc de presentar-la com si fos un valor exacte.</p>
<p>La funció <code>predict()</code> permet calcular aquest interval afegint l’argument interval, que pot prendre dos valors:</p>
<p>-<code>predict(model_cultura, newdata = nou_municipi, interval = "confidence")</code></p>
<p>-<code>predict(model_cultura, newdata = nou_municipi, interval = "prediction")</code></p>
<p>És important distingir entre els dos tipus d’interval, ja que responen a preguntes diferents:</p>
<p>-interval de confiança (interval = “confidence”): informa sobre la incertesa al voltant del valor mitjà esperat d’assistència per a municipis amb aquest nivell d’equipaments culturals. És a dir, respon a la pregunta: «si tinguéssim molts municipis amb 1,7 equipaments per 10.000 habitants, en quin rang se situaria l’assistència mitjana d’aquest conjunt?»</p>
<p>-interval de predicció (interval = “prediction”): informa sobre la incertesa al voltant del valor esperat per a un municipi individual concret. Respon a la pregunta: «quin rang d’assistència podem esperar per a aquest municipi en particular?»</p>
<p>L’interval de predicció sempre serà més ampli que l’interval de confiança, ja que a la incertesa sobre la mitjana s’hi suma la variabilitat pròpia de cada observació individual. En la pràctica, quan volem predir un valor concret (com en el nostre exemple, un nou municipi), l’interval de predicció sol ser el més rellevant, mentre que l’interval de confiança és més adequat quan volem estimar el comportament mitjà d’un grup d’observacions amb característiques similars.</p>
<p>Presentar les prediccions acompanyades del seu interval, en lloc d’un únic valor, és una bona pràctica que ajuda a comunicar honestament el grau de certesa (o incertesa) que té el nostre model, especialment tenint en compte la mida reduïda de la mostra amb què treballem en aquest exemple.</p>
<section id="supòsits-de-la-regressió-lineal" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="supòsits-de-la-regressió-lineal"><span class="header-section-number">3.1</span> Supòsits de la regressió lineal</h2>
<p>Perquè els resultats d’un model de regressió lineal (els coeficients, els p-valors, els intervals de confiança) siguin fiables, cal que es compleixin una sèrie de supòsits bàsics. Fins ara ens hem centrat a interpretar el model, però és igualment important validar-lo, és a dir, comprovar que aquests supòsits es compleixen raonablement bé. Els quatre supòsits principals són:</p>
<p>-linealitat: la relació entre les variables predictores i la variable resposta ha de ser aproximadament lineal. Si la relació real fos, per exemple, corba, un model lineal no la captaria correctament.</p>
<p>-normalitat dels residus: els residus del model (la diferència entre els valors observats i els valors predits) han de seguir, aproximadament, una distribució normal. Aquest supòsit és especialment rellevant per a la validesa dels contrastos d’hipòtesi (p-valors) del model.</p>
<p>-homocedasticitat: la variabilitat dels residus ha de ser constant al llarg de tot el rang de valors predits. Quan això no es compleix (és a dir, quan els residus són més dispersos per a alguns valors que per a d’altres), es parla d’heterocedasticitat i pot indicar que el model no és adequat o que caldria transformar alguna variable.</p>
<p>-independència dels residus: els residus no haurien d’estar correlacionats entre si. Aquest supòsit sol ser especialment rellevant en dades temporals o seqüencials, on una observació pot estar influenciada per l’anterior.</p>
<p>En R, una manera ràpida i molt visual de comprovar aquests supòsits és representar gràficament el model amb la funció <code>plot()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(model_cultura)</span></code></pre></div><button title="Copia al porta-retalls" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tema_05_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tema_05_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tema_05_files/figure-html/unnamed-chunk-6-3.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="tema_05_files/figure-html/unnamed-chunk-6-4.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Aquesta funció genera quatre gràfics de diagnòstic:</p>
<p>-<em>Residuals vs Fitted</em>: permet detectar problemes de linealitat i d’homocedasticitat. Idealment, els punts s’haurien de distribuir de manera aleatòria al voltant de la línia horitzontal de zero, sense cap patró clar.</p>
<p>-<em>Q-Q Residuals</em>: compara la distribució dels residus amb una distribució normal teòrica. Si els punts s’ajusten aproximadament a la línia diagonal, es pot considerar que el supòsit de normalitat es compleix raonablement.</p>
<p>-<em>Scale-Location</em>: similar al primer gràfic, però útil específicament per detectar problemes d’homocedasticitat. Els punts s’haurien de distribuir de manera uniforme al llarg de l’eix horitzontal.</p>
<p>-<em>Residuals vs Leverage</em>: permet identificar observacions atípiques o influents que podrien estar condicionant excessivament els resultats del model.</p>
<p>Cal remarcar que, amb mostres petites (com la de només 10 municipis del nostre exemple), aquests gràfics de diagnòstic tenen un valor limitat, ja que és difícil valorar amb garanties si es compleix un supòsit amb tan poques observacions. No obstant això, és una bona pràctica revisar-los sempre, especialment quan es treballa amb mostres més grans, per assegurar-nos que les conclusions extretes del model són fiables i no estan condicionades per un incompliment greu d’algun d’aquests supòsits.</p>
</section>
</section>
<section id="regressió-lineal-múltiple" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Regressió lineal múltiple</h1>
<p>A més dels equipaments culturals, afegirem una segona variable: la despesa pública cultural (euros anuals) per habitant de cada municipi.</p>
<p>La taula mostra el dataset actualitzat.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>cultura.act <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">municipi =</span> <span class="fu">paste0</span>(<span class="st">"M"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>),</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>                          <span class="at">equipaments_per_10k =</span> <span class="fu">c</span>(<span class="fl">1.2</span>, <span class="fl">0.8</span>, <span class="fl">2.0</span>, <span class="fl">1.5</span>, <span class="fl">2.3</span>, <span class="fl">0.6</span>, <span class="fl">1.8</span>, <span class="fl">2.6</span>, <span class="fl">1.0</span>, <span class="fl">2.1</span>),</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">despesa_cultural =</span> <span class="fu">c</span>(<span class="dv">85</span>, <span class="dv">60</span>, <span class="dv">120</span>, <span class="dv">95</span>, <span class="dv">130</span>, <span class="dv">55</span>, <span class="dv">110</span>, <span class="dv">150</span>, <span class="dv">70</span>, <span class="dv">125</span>),</span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">assistencia_per_1000 =</span> <span class="fu">c</span>(<span class="dv">45</span>, <span class="dv">30</span>, <span class="dv">70</span>, <span class="dv">55</span>, <span class="dv">80</span>, <span class="dv">25</span>, <span class="dv">65</span>, <span class="dv">90</span>, <span class="dv">35</span>, <span class="dv">75</span>))</span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>cultura.act</span></code></pre></div><button title="Copia al porta-retalls" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div data-pagedtable="false">
  <script data-pagedtable-source="" type="application/json">
{"columns":[{"label":["municipi"],"name":[1],"type":["chr"],"align":["left"]},{"label":["equipaments_per_10k"],"name":[2],"type":["dbl"],"align":["right"]},{"label":["despesa_cultural"],"name":[3],"type":["dbl"],"align":["right"]},{"label":["assistencia_per_1000"],"name":[4],"type":["dbl"],"align":["right"]}],"data":[{"1":"M1","2":"1.2","3":"85","4":"45"},{"1":"M2","2":"0.8","3":"60","4":"30"},{"1":"M3","2":"2.0","3":"120","4":"70"},{"1":"M4","2":"1.5","3":"95","4":"55"},{"1":"M5","2":"2.3","3":"130","4":"80"},{"1":"M6","2":"0.6","3":"55","4":"25"},{"1":"M7","2":"1.8","3":"110","4":"65"},{"1":"M8","2":"2.6","3":"150","4":"90"},{"1":"M9","2":"1.0","3":"70","4":"35"},{"1":"M10","2":"2.1","3":"125","4":"75"}],"options":{"columns":{"min":{},"max":[10]},"rows":{"min":[10],"max":[10]},"pages":{}}}
  </script>
</div>
</div>
</div>
<p>En aquest cas, el model prendrà la següent forma:</p>
<p><span class="math display">\[
Assistència = a + \beta_1 \cdot Equipaments + \beta_2 \cdot Despesa
\]</span></p>
<p>Construïm el model:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>model_multiple <span class="ot">&lt;-</span> <span class="fu">lm</span>(assistencia_per_1000 <span class="sc">~</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>                       equipaments_per_10k <span class="sc">+</span> </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>                       despesa_cultural,</span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">data =</span> cultura.act)</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_multiple)</span></code></pre></div><button title="Copia al porta-retalls" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = assistencia_per_1000 ~ equipaments_per_10k + despesa_cultural, 
    data = cultura.act)

Residuals:
    Min      1Q  Median      3Q     Max 
-1.8203 -0.5988  0.1987  0.7095  1.1950 

Coefficients:
                    Estimate Std. Error t value Pr(&gt;|t|)  
(Intercept)          -2.6603     4.1505  -0.641   0.5420  
equipaments_per_10k  20.1908     7.8344   2.577   0.0366 *
despesa_cultural      0.2756     0.1647   1.673   0.1382  
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.116 on 7 degrees of freedom
Multiple R-squared:  0.9981,    Adjusted R-squared:  0.9975 
F-statistic:  1827 on 2 and 7 DF,  p-value: 3.055e-10</code></pre>
</div>
</div>
<p>El coeficient associat a equipaments_per_10k és positiu i estadísticament significatiu (β = 20.19; p = 0.0366). Això indica que, mantenint constant la despesa cultural, un increment d’un equipament cultural per cada 10.000 habitants s’associa amb un augment aproximat de 20 persones per 1.000 habitants en l’assistència anual.</p>
<p>Pel que fa a la despesa cultural per habitant, el coeficient estimat és positiu (β = 0.276), cosa que indica que, mantenint constant el nombre d’equipaments, cada euro addicional de despesa cultural s’associa amb un increment aproximat de 0,28 persones per 1.000 habitants en l’assistència. No obstant, aquest coeficient no és estadísticament significatiu al nivell convencional del 5% (p = 0.138), fet que implica que, amb aquesta mostra, no podem afirmar que la despesa tingui un efecte independent clar sobre l’assistència.</p>
<p>L’intercept (a = −2.66) tampoc no és estadísticament significatiu (p = 0.542) i no té una interpretació substantiva rellevant, ja que correspondria al nivell d’assistència quan ambdues variables explicatives prenen el valor zero, una situació que no és real.</p>
<p>El model presenta un coeficient de determinació molt elevat (R² = 0.99), fet que indica que el 99% de la variabilitat observada en l’assistència és explicada conjuntament per les dues variables incloses.</p>
<p>Fins ara hem fet servir el coeficient de determinació (R²) per valorar la qualitat de l’ajust dels nostres models. No obstant, en passar a la regressió múltiple, cal tenir en compte una particularitat important d’aquest indicador: el R² sempre augmenta (o, com a mínim, no disminueix) a mesura que afegim més variables predictores al model, encara que aquestes variables noves no tinguin cap relació real amb la variable resposta. Això succeeix perquè el model sempre pot aprofitar una mica més de variabilitat “per atzar” en afegir una dimensió addicional, encara que aquesta variable no aporti informació rellevant.</p>
<p>Aquesta propietat converteix el R² en un indicador poc fiable per decidir si val la pena afegir una variable a un model, ja que sempre “premiarà” el model més complex. Per solucionar-ho, R calcula també el R² ajustat (<em>Adjusted R-squared</em>), que es mostra just a sota del R² a la sortida de <code>summary()</code>. A diferència del R² normal, el R² ajustat penalitza l’increment del nombre de variables, de manera que només augmenta si la variable nova aporta més capacitat explicativa de la que s’esperaria per atzar. Si afegim una variable poc útil, el R² ajustat pot fins i tot disminuir, malgrat que el R² normal hagi augmentat.</p>
<p>Per aquest motiu, quan es comparen models amb un nombre diferent de variables (com és el nostre cas: el model simple amb una variable i el model múltiple amb dues), és més adequat fixar-nos en el R² ajustat que no pas en el R² normal. Si comparem els dos models del nostre exemple, podem observar que el R² ajustat del model múltiple manté un valor molt similar (o lleugerament superior) al del model simple, cosa que confirma que la variable despesa_cultural aporta una millora real i no merament aparent en la capacitat explicativa del model.</p>
<p>En la pràctica, el R² ajustat és especialment útil quan es té diverses variables candidates i cal decidir quines val la pena incloure en el model final: una bona regla general és desconfiar de les variables que, en afegir-les, incrementen el R² però no el R² ajustat, ja que probablement no estan aportant informació rellevant.</p>
<p>En conjunt, els resultats indiquen que la quantitat d’equipaments culturals manté un efecte positiu sobre la participació cultural fins i tot quan es controla la despesa pública. En canvi, la despesa cultural mostra una associació positiva però no significativa en presència de la variable d’equipaments. Això podria suggerir que la infraestructura cultural té un paper més estructural en l’explicació de l’assistència, o bé que existeix una certa correlació entre ambdues variables que dificulta la separació neta dels seus efectes en una mostra tan reduïda.</p>
<p>El dubte que acabem de plantejar (si l’efecte no significatiu de la despesa cultural es deu a una manca real d’influència o, més aviat, a una correlació entre les dues variables predictores) fa referència a un problema molt habitual en regressió múltiple conegut com a multicolinealitat. Es produeix quan dues o més variables explicatives estan fortament correlacionades entre si, cosa que dificulta que el model pugui distingir l’efecte independent de cadascuna sobre la variable resposta. En el nostre exemple, és raonable pensar que els municipis amb més equipaments culturals també tendeixen a destinar-hi més pressupost, de manera que ambdues variables es mouen sovint juntes.</p>
<p>La multicolinealitat no afecta la capacitat predictiva global del model (el R² es manté igual d’elevat), però sí que pot fer que els coeficients individuals siguin inestables, difícils d’interpretar o, com hem vist, no estadísticament significatius encara que la variable sigui rellevant en realitat.</p>
<p>Acabarem amb un exemple de predicció corresponent a un nou municipi amb 1.7 equipaments per 10.000 habitants i 100 € de despesa cultural per habitant</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>nou_municipi <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">equipaments_per_10k =</span> <span class="fl">1.7</span>,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">despesa_cultural =</span> <span class="dv">100</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(model_multiple, <span class="at">newdata =</span> nou_municipi)</span></code></pre></div><button title="Copia al porta-retalls" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1 
59.22099 </code></pre>
</div>
</div>
<p>Això significa que el model prediu una assistència aproximada de 59,2 persones per cada 1.000 habitants en activitats culturals per a un municipi amb aquestes característiques. A diferència de la regressió simple, aquesta estimació té en compte simultàniament l’efecte de la infraestructura cultural i el nivell de despesa pública. Per tant, la predicció reflecteix l’efecte combinat d’ambdues variables, mantenint constant l’impacte de cadascuna mentre s’estima l’altra.</p>
</section>
<section id="exercici" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Exercici</h1>
<p>Una web de ressenyes de restaurants publica un conjunt de dades que inclou, per a 15 restaurants, la valoració de tres dimensions específiques (menjar, ambient i servei) així com la puntuació global atorgada pels clients. El dataset està disponible al Campus Virtual.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>   menjar ambient servei puntuacio
1      85      82     89        78
2      80      90     80        85
3      83      86     83        85
4      70      96     75        72
5      68      80     78        75
6      65      70     56        54
7      64      68     61        62
8      72      95     72        73
9      69      70     78        70
10     75      80     75        77
11     75      70     75        74
12     72      90     78        76
13     81      72     78        80
14     71      91     71        71
15     67      86     78        64</code></pre>
</div>
</div>
<p>Calcula la correlació entre cadascuna de les tres dimensions (menjar, ambient i servei) i la puntuació global, i determina quina d’elles presenta una associació més forta amb la valoració global.</p>
<p>A continuació, construeix un model de regressió lineal múltiple utilitzant la puntuació global com a variable dependent i les tres dimensions com a variables explicatives.</p>
<p>Fent servir el model estimat, calcula la puntuació global prevista per a un restaurant que obté les següents valoracions:</p>
<p>Menjar: 90</p>
<p>Ambient: 70</p>
<p>Servei: 80</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiat!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiat!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>